### PR TITLE
Reformat 1.12 port

### PR DESCRIPTION
**Pull request by Rikshy**
I hope this is better this time.

it still missed advancements and jei descriptions.

### CODE REVIEW

**Comment by Daomephsta** [comment]
This is mostly fine, thanks for taking the time to do it. However there are a few issues:

* You've removed the JSON recipe system. Yes, the CraftTweaker support does the same stuff, however the JSON recipe system exists for a reason. Due to the large changes to crafting made by BB, it's important that there's a first party method of changing the recipes.

* You removed the fuel registry for some reason and replaced calls to it with calls to `TileEntityFurnace.getItemBurnTime()`. Items do not burn for the same length of time in the furnace and in the various specialised furnaces, so the calls are not equivalent. The fuel registry also allows users to modify burn times of items in any of the specialised furnaces (except for the nether brick oven IIRC). 

* You seem to have accidentally corrupted the Chinese and Russian translations.

* You've also merged the item handlers for the advanced furnaces with the item handlers for the basic furnaces. Why? It's unnecessary for the port.

**Comment by Rikshy** [comment]
- As i said in the commit notes i had a crash i couldn't resolve (it's been a month or more when i did this, so i dunno no know what exactly it was). figuered it would be easier to remove it and maybe add it back later.

- The FuelRegistry is depricated
By subscribing to this event, you can set the burntime
```
@SubscribeEvent
public void onFurnaceFuelTime(final FurnaceFuelBurnTimeEvent event) 
{
	event.setBurnTime(calculateFuelBurnTime(event.getItemStack()));
}

// Set -1 for default
protected abstract int calculateFuelBurnTime(final ItemStack fuelStack);
```
there were a lot more deprecated methods i resolved, but my HDD died on me and after i got a new one i wasn't motivated to do it again :/

- initially i just ported this mod to get a grip on modding eventually deciding it wouldn't be too bad to share it and maybe get some hints and tipps what might be wrong or right. I did remove most of optimization and rewrites to make it a clean port. i didnt think this small change would be that big of a deal so i kept it.

**Comment by Daomephsta** [comment]
> The FuelRegistry is depricated

No it isn't. [Look at it](https://github.com/einsteinsci/BetterBeginningsReborn/blob/e5f97f821795650ca7481dca9065bff405417af2/src/main/java/net/einsteinsci/betterbeginnings/register/FuelRegistry.java), no @Deprecated annotations anywhere.

**Comment by Rikshy** [comment]
I just saw that [FuelMap](https://github.com/einsteinsci/BetterBeginningsReborn/blob/e5f97f821795650ca7481dca9065bff405417af2/src/main/java/net/einsteinsci/betterbeginnings/register/FuelMap.java) (which is used by [FuelRegistry](https://github.com/einsteinsci/BetterBeginningsReborn/blob/e5f97f821795650ca7481dca9065bff405417af2/src/main/java/net/einsteinsci/betterbeginnings/register/FuelRegistry.java#L33)) has the depricated [IFuelHandler](https://github.com/einsteinsci/BetterBeginningsReborn/blob/e5f97f821795650ca7481dca9065bff405417af2/src/main/java/net/einsteinsci/betterbeginnings/register/FuelMap.java#L29). tbh i didnt put much thoughts in it and just used the advertised way.

**Comment by Daomephsta** [comment]
Aah I see. Just revert it to how it was before. I'll look at fixing it.

**Comment by einsteinsci** [comment]
Archiving long-abandoned project. If you want to continue development, you are free to do so on your fork. See README.md for details.

**Pull request closed without merging**
