### PR TITLE
"completed" port to 1.12

### PR DESCRIPTION
**Pull request by Rikshy**
it's basically just a running version. no new features or sth.
Far from perfect tho

### CODE REVIEW

**Comment by Daomephsta** [comment]
Your formatter wasn't disabled. It's reformatted much of the code you touched. Please fix this, it makes it rather difficult to see what you changed.

**Comment by Rikshy** [comment]
i am currently at work, will do later today. Imho it's more readable that way, but will do.

**Comment by Rikshy** [comment]
can you export your IDEA! or Eclipse (what ever you are using) format settings?

i am a C# dev and just used the standard formatting IntelliJ had to offer.

**Comment by Daomephsta** [comment]
When contributing to an open source project, you always stick to its style and formatting. Otherwise the codebase has an inconsistent style and PRs are hard to review because people keep changing the formatting of any file they touch.

I don't actually have a valid formatter for BB's style ATM, it's been a while since I've worked on BB. I'll send you the style and format spec in the morning.

**Comment by Rikshy** [comment]
I see your point, makes sense. I will respect that in the future!

Thanks :)

**Comment by Daomephsta** [comment]
Ok, so I've actually realised I forgot some of the format rules myself, so BB doesn't have an entirely consistent style. So here's the intersection of my coding style and einsteinsci's original spec, which the BB codebase should follow:

* Tabs not spaces
* Braces on new lines
* Any more than three imports from the same package should use .* syntax
* Line comments should have a space after the `//`
* All overriden methods should be annotated with `@Override`
* Method annotations should be on a separate line to the method
* All interface names should be prefixed with I
* Use the Java 7 "diamond operator" for generic constructors: e.g `List<Item> items = new ArrayList<>()`;

Also turn off auto format, and don't apply these guidelines to any code you aren't writing/rewriting. Code that doesn't follow the guidelines can be dealt with later.

**Comment by Rikshy** [comment]
did a new pull request

**Pull request closed without merging**
